/**
 * ═══════════════════════════════════════════════════════════════
 * CustomReporter - Framework Reporting Hooks
 * ═══════════════════════════════════════════════════════════════
 *
 * Plugs into WebdriverIO / Cucumber lifecycle events to augment
 * reports with extra metadata, environment info, screenshots,
 * and performance data.
 */

const path = require('path');
const fs = require('fs-extra');
const { Logger } = require('./Logger');

const logger = Logger.getInstance('Reporter');

class CustomReporter {
    /**
     * Attach a screenshot to the Allure / Cucumber report.
     */
    static async attachScreenshot(name = 'screenshot') {
        try {
            const screenshot = await browser.takeScreenshot();
            const cucumberJson = require('wdio-cucumberjs-json-reporter').default;
            cucumberJson.attach(screenshot, 'image/png');
            logger.info(`Screenshot attached: ${name}`);
        } catch (error) {
            logger.warn(`Failed to attach screenshot: ${error.message}`);
        }
    }

    /**
     * Attach arbitrary text to the report.
     */
    static attachText(text, mimeType = 'text/plain') {
        try {
            const cucumberJson = require('wdio-cucumberjs-json-reporter').default;
            cucumberJson.attach(text, mimeType);
        } catch (error) {
            logger.warn(`Failed to attach text: ${error.message}`);
        }
    }

    /**
     * Attach a JSON object to the report (pretty-printed).
     */
    static attachJSON(data, name = 'data') {
        this.attachText(JSON.stringify(data, null, 2), 'application/json');
    }

    /**
     * Attach environment / browser information to the report.
     */
    static async attachEnvironmentInfo() {
        try {
            const caps = await browser.capabilities;
            const info = {
                browser: caps.browserName,
                browserVersion: caps.browserVersion,
                platform: caps.platformName,
                baseUrl: browser.options.baseUrl,
                environment: process.env.TEST_ENV || 'unknown',
                nodeVersion: process.version,
                timestamp: new Date().toISOString(),
            };
            this.attachJSON(info, 'environment');
        } catch (error) {
            logger.warn(`Failed to attach env info: ${error.message}`);
        }
    }

    /**
     * Write Allure environment.properties file for the environment tab.
     */
    static writeAllureEnvironment(outputDir) {
        const props = [
            `Browser=${process.env.BROWSER || 'chrome'}`,
            `Environment=${process.env.TEST_ENV || 'dev'}`,
            `BaseURL=${process.env.BASE_URL || 'N/A'}`,
            `NodeVersion=${process.version}`,
            `Platform=${process.platform}`,
            `Date=${new Date().toISOString()}`,
        ].join('\n');

        const envFile = path.join(outputDir, 'environment.properties');
        fs.ensureDirSync(outputDir);
        fs.writeFileSync(envFile, props);
        logger.info('Allure environment.properties written');
    }

    /**
     * Write Allure categories.json for defect classification.
     */
    static writeAllureCategories(outputDir) {
        const categories = [
            {
                name: 'Element Not Found',
                matchedStatuses: ['broken'],
                messageRegex: '.*no such element.*|.*element not interactable.*',
            },
            {
                name: 'Timeout Failures',
                matchedStatuses: ['broken'],
                messageRegex: '.*timeout.*|.*Timed out.*',
            },
            {
                name: 'Assertion Failures',
                matchedStatuses: ['failed'],
                messageRegex: '.*AssertionError.*|.*expected.*to.*',
            },
            {
                name: 'Infrastructure Issues',
                matchedStatuses: ['broken'],
                messageRegex: '.*ECONNREFUSED.*|.*net::ERR.*|.*session not created.*',
            },
        ];

        const catFile = path.join(outputDir, 'categories.json');
        fs.ensureDirSync(outputDir);
        fs.writeFileSync(catFile, JSON.stringify(categories, null, 2));
        logger.info('Allure categories.json written');
    }

    /**
     * Generate the Cucumber HTML report from JSON results.
     */
    static generateCucumberHtmlReport(jsonDir, outputDir) {
        try {
            const report = require('multiple-cucumber-html-reporter');
            report.generate({
                jsonDir,
                reportPath: outputDir,
                reportName: 'Test Automation Report',
                pageTitle: 'E2E Test Results',
                displayDuration: true,
                displayReportTime: true,
                openReportInBrowser: false,
                pageFooter: '<p>Generated by Enterprise WDIO Cucumber Framework</p>',
                customData: {
                    title: 'Run Information',
                    data: [
                        { label: 'Project', value: 'Enterprise Framework' },
                        { label: 'Environment', value: process.env.TEST_ENV || 'dev' },
                        { label: 'Browser', value: process.env.BROWSER || 'chrome' },
                        { label: 'Execution Date', value: new Date().toLocaleString() },
                        { label: 'Node Version', value: process.version },
                        { label: 'Platform', value: `${process.platform} ${process.arch}` },
                    ],
                },
            });
            logger.info(`Cucumber HTML report generated at: ${outputDir}`);
        } catch (error) {
            logger.error(`Failed to generate Cucumber HTML report: ${error.message}`);
        }
    }
}

module.exports = { CustomReporter };
