/**
 * ═══════════════════════════════════════════════════════════════
 * Generate Report - Post-Execution Report Generator
 * ═══════════════════════════════════════════════════════════════
 *
 * Run with: npm run report:generate
 */

const path = require('path');
const fs = require('fs-extra');

const ROOT = process.cwd();
const REPORTS_DIR = path.join(ROOT, 'reports');
const CUCUMBER_JSON = path.join(REPORTS_DIR, 'cucumber-json');
const CUCUMBER_HTML = path.join(REPORTS_DIR, 'cucumber-html');

console.log('═══════════════════════════════════════════');
console.log(' Report Generation');
console.log('═══════════════════════════════════════════');

// ─── Cucumber HTML Report ─────────────────────────────────────
try {
    const jsonFiles = fs.readdirSync(CUCUMBER_JSON).filter((f) => f.endsWith('.json'));

    if (jsonFiles.length === 0) {
        console.log('⚠  No Cucumber JSON files found. Run tests first.');
        process.exit(0);
    }

    const report = require('multiple-cucumber-html-reporter');

    report.generate({
        jsonDir: CUCUMBER_JSON,
        reportPath: CUCUMBER_HTML,
        reportName: 'E2E Test Automation Report',
        pageTitle: 'Test Results Dashboard',
        displayDuration: true,
        displayReportTime: true,
        openReportInBrowser: true,
        pageFooter: '<div style="text-align:center;padding:10px;"><p>Generated by Enterprise WDIO Framework</p></div>',
        customData: {
            title: 'Execution Summary',
            data: [
                { label: 'Project', value: 'Enterprise Test Framework' },
                { label: 'Environment', value: process.env.TEST_ENV || 'dev' },
                { label: 'Browser', value: process.env.BROWSER || 'chrome' },
                { label: 'Platform', value: `${process.platform} ${process.arch}` },
                { label: 'Node Version', value: process.version },
                { label: 'Execution Date', value: new Date().toLocaleString() },
            ],
        },
        customMetadata: true,
    });

    console.log(`✓  Cucumber HTML report: ${CUCUMBER_HTML}`);
} catch (error) {
    console.error(`✗  Cucumber report error: ${error.message}`);
}

// ─── Summary ──────────────────────────────────────────────────
console.log('');
console.log('Available reports:');
console.log(`  Cucumber HTML : ${CUCUMBER_HTML}/index.html`);
console.log(`  Allure        : Run "npm run report:allure" to generate`);
console.log(`  Timeline      : ${path.join(REPORTS_DIR, 'timeline')}/timeline-report.html`);
console.log('');
console.log('═══════════════════════════════════════════');
